[pie]
moo ansible_host=100.76.6.76 ansible_user=ubuntu
#moo ansible_host=100.76.6.76 ansible_user=ubuntu

# AWS virtual machine reachable by tailscale [ local network ]
vm ansible_host=ip-10-0-1-47  ansible_user=root
