---

- name: Check connectivity to the machine
  hosts: all
  become: false # run as root user

  tasks:
    - name: Ping the machine
      ansible.builtin.ping:

- name: Perform user creation
  hosts: all
  become: true
  vars:
    lab_user: breakme

  tasks:
    - name: Create the user - breakme
      ansible.builtin.user:
         name: "{{ lab_user }}"
         create_home: true

    - name: Create file for breakme user
      ansible.builtin.file:
         path: "/home/{{ lab_user }}/hello.txt"
         owner: 1006
         state: touch
